# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import protos.game_pb2 as game__pb2


class StatusStub(object):
    """Missing associated documentation comment in .proto file"""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.test = channel.unary_unary(
                '/game.Status/test',
                request_serializer=game__pb2.StatusRequest.SerializeToString,
                response_deserializer=game__pb2.StatusResponse.FromString,
                )


class StatusServicer(object):
    """Missing associated documentation comment in .proto file"""

    def test(self, request, context):
        """Missing associated documentation comment in .proto file"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_StatusServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'test': grpc.unary_unary_rpc_method_handler(
                    servicer.test,
                    request_deserializer=game__pb2.StatusRequest.FromString,
                    response_serializer=game__pb2.StatusResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'game.Status', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Status(object):
    """Missing associated documentation comment in .proto file"""

    @staticmethod
    def test(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/game.Status/test',
            game__pb2.StatusRequest.SerializeToString,
            game__pb2.StatusResponse.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)
